%% fig 2: meridional cross sections of zonal velocity differences
clearvars('-except', '*_path')
play(bird_i_path,[1 (get(bird_i_path, 'SampleRate')*3)]);

load([data_path 'SACS_data/aus8_coor'])
load([data_path 'SACS_data/aus8_currents'])
load([data_path 'SACS_data/aus8_figures'])
load([data_path 'SACS_data/aus8_u_g_prime'])
load([data_path 'SACS_data/aus8_v_g_prime'])
load([data_path 'SACS_data/KDau_u_g_prime'])
load([data_path 'SACS_data/KDau_v_g_prime'])


%% plot map
depth_mid_for_plot = aus8_coor.depth_mid;
depth_mid_for_plot(end) = -2000;
lon_u_SBC_north_OK = ...
    [aus8_currents.nudging.north.west_GAB.lon_u_east : 1/8 : ...
    aus8_currents.nudging.north.eGs_wBS.lon_u_west, ...
    aus8_currents.nudging.north.eGs_wBS.lon_u_east : 1/8 : ...
    aus8_currents.nudging.north.sBS_wT.lon_u_west];

fig_n = 1;
rowcols = [2 4];
rowcols_size = [6 10]; % cm
margs = [1.5 2.5 1.2 1.2]; % cm
gaps = [1 1.75]; % cm
plot_cbar_gap = 0.5;
cbar_x = 0.3;
cbar_y = rowcols_size(2);

magnif = 100;
cmap1_cont = (-12 : 2 : 0);
cmap2_cont = (0 : 4 : 20);
lvl_cmap1 = length(cmap1_cont)-1;
lvl_cmap2 = length(cmap2_cont)-1;
cmap1 = flipud(othercolor('Blues6', lvl_cmap1));
cmap2 = othercolor('Reds6', lvl_cmap2);
cmaps = [cmap1; cmap2];
cmaps_cont = [cmap1_cont cmap2_cont(2:end)];
cmaps_cont_length = length(cmaps_cont);
cmaps_linspace = linspace(0,1,cmaps_cont_length);
cmaps_y_label = cmaps_cont;

for sp = 1 : rowcols(1)*rowcols(2)
    minmax{sp} = [cmaps_cont(1) cmaps_cont(end)];
    cmaps_custom{sp} = cmapcust(cmaps,cmaps_cont);
    
    axis_setup{sp} = [...
        aus8_figures.cross.lat(2,sp), ...
        aus8_figures.cross.lat(1,sp), ...
        -2000, ...
        0];
    x{sp} = aus8_coor.lat_u;
    y{sp} = depth_mid_for_plot;
    data{sp} = squeeze(aus8_u_g_prime.mean...
        (:,aus8_coor.lon_u == aus8_figures.cross.lon(1,sp),:))'*magnif;
    data_contour{sp} = squeeze(aus8_v_g_prime.mean...
        (:,aus8_coor.lon_v == aus8_figures.cross.lon(1,sp)+1/16,:))'...
        *magnif;
    x_contour{sp} = aus8_coor.lat_v;
end

lett = 'a':'z';
font_size = 13;
fig_color = [0.7 0.7 0.7];

close all
fig = figure(fig_n);
rowN = rowcols(1); colN = rowcols(2);
[rm, cm] = meshgrid(rowN:-1:1, 1:colN);
x_sp = rowcols_size(1); % x subplot length
y_sp = rowcols_size(2); % y subplot length
col_ind = (repmat(1:colN,rowN,1))';
row_ind = (fliplr(repmat((1:rowN)',1,colN)))';
gap_w = gaps(1); % gap width between subplots
gap_h = gaps(2); % gap height between subplots
marg_b = margs(3); % bottom margin
marg_t = margs(4); % top margin
marg_l = margs(1); % left margin
marg_r = margs(2); % right margin
set(fig,'units','centimeters',...
    'position',[0 0 ...
    (marg_l+colN*x_sp+gap_w*(colN-1)+marg_r) ...
    (marg_b+rowN*y_sp+gap_h*(rowN-1)+marg_t)]);

for sp = 1 : rowN*colN
    ax = axes('Units','centimeters', ...
        'Position',[...
        (marg_l+x_sp*(cm(sp)-1)+gap_w*(cm(sp)-1)), ...
        (marg_b+y_sp*(rm(sp)-1)+gap_h*(rm(sp)-1)), ...
        x_sp, ...
        y_sp]);
    
    colormap(ax, cmaps_custom{sp});
    pcolor(x{sp}, y{sp}, data{sp})
    axis(axis_setup{sp})
    shading interp
    caxis([minmax{sp}(1) minmax{sp}(2)]);
    hold on
    
    [cn, hn] = contour(x_contour{sp},y{sp},data_contour{sp}, ...
        -20 : 2 : -2,'--k');
    clabel(cn, hn,'manual','fontsize',font_size)
    
    [cn, hn] = contour(x_contour{sp},y{sp},data_contour{sp}, ...
        0 : 2 : 20,'-k');
    clabel(cn, hn,'manual','fontsize',font_size)
    
    line_width = 0.1;
    contour(x{sp},y{sp},data{sp}, ...
        cmaps_cont,'-k','linewidth', line_width);
    
    line_width = 2;
    if find(ismember(lon_u_SBC_north_OK,aus8_figures.cross.lon(1,sp)))
        plot([...
            aus8_currents.lat_v_SBC_north(...
            aus8_currents.lon_u_ALLC==aus8_figures.cross.lon(1,sp)),...
            aus8_currents.lat_v_SBC_north(...
            aus8_currents.lon_u_ALLC==aus8_figures.cross.lon(1,sp))],...
            [aus8_currents.z_mid, aus8_currents.z_top], 'g', ...
            'linewidth',line_width)
    end
    
    if aus8_figures.cross.lon(1,sp)~=147
        plot([...
            aus8_currents.lat_v_SBC_south(...
            aus8_currents.lon_u_ALLC==aus8_figures.cross.lon(1,sp)),...
            aus8_currents.lat_v_SBC_north(...
            aus8_currents.lon_u_ALLC==aus8_figures.cross.lon(1,sp))],...
            [aus8_currents.z_mid, aus8_currents.z_mid], 'b', ...
            'linewidth',line_width)
    else
        plot([...
            aus8_currents.lat_v_SBC_south(end),...
            aus8_currents.lat_v_SBC_north(end)],...
            [aus8_currents.z_mid, aus8_currents.z_mid], 'b', ...
            'linewidth',line_width)
    end
    
    if aus8_figures.cross.lon(1,sp)~=147
        plot([...
            aus8_currents.lat_v_SBC_south(...
            aus8_currents.lon_u_ALLC==aus8_figures.cross.lon(1,sp)),...
            aus8_currents.lat_v_SBC_south(...
            aus8_currents.lon_u_ALLC==aus8_figures.cross.lon(1,sp))],...
            [aus8_currents.z_mid, aus8_currents.z_top], 'r', ...
            'linewidth',line_width)
    else
        plot([...
            aus8_currents.lat_v_SBC_south(end),...
            aus8_currents.lat_v_SBC_south(end)],...
            [aus8_currents.z_mid, aus8_currents.z_top], 'r', ...
            'linewidth',line_width)
    end
    
    if aus8_figures.cross.lon(1,sp)~=147
        plot([...
            aus8_currents.lat_v_DRC_south(...
            aus8_currents.lon_u_ALLC==aus8_figures.cross.lon(1,sp)),...
            aus8_currents.lat_v_DRC_south(...
            aus8_currents.lon_u_ALLC==aus8_figures.cross.lon(1,sp))],...
            [aus8_currents.z_mid, aus8_currents.z_top], ...
            '--m', ...
            'linewidth',line_width)
    else
        plot([...
            aus8_currents.lat_v_DRC_south(end),...
            aus8_currents.lat_v_DRC_south(end)],...
            [aus8_currents.z_mid, aus8_currents.z_top], ...
            '--m', ...
            'linewidth',line_width)
    end
    
    if aus8_figures.cross.lon(1,sp)~=147
        plot([...
            aus8_currents.lat_v_DRC_south(...
            aus8_currents.lon_u_ALLC==aus8_figures.cross.lon(1,sp)),...
            aus8_currents.lat_v_DRC_south(...
            aus8_currents.lon_u_ALLC==aus8_figures.cross.lon(1,sp))],...
            [aus8_currents.z_bot, aus8_currents.z_mid], ...
            ':m', ...
            'linewidth',line_width)
    else
        plot([...
            aus8_currents.lat_v_DRC_south(end),...
            aus8_currents.lat_v_DRC_south(end)],...
            [aus8_currents.z_bot, aus8_currents.z_mid], ...
            ':m', ...
            'linewidth',line_width)
    end
    
    if aus8_figures.cross.lon(1,sp)~=147
        plot([...
            aus8_currents.lat_v_DRC_south(...
            aus8_currents.lon_u_ALLC==aus8_figures.cross.lon(1,sp)),...
            aus8_currents.lat_v_SBC_north(...
            aus8_currents.lon_u_ALLC==aus8_figures.cross.lon(1,sp))],...
            [aus8_currents.z_bot, aus8_currents.z_bot], ...
            'm', ...
            'linewidth',line_width)
    else
        plot([...
            aus8_currents.lat_v_DRC_south(end),...
            aus8_currents.lat_v_SBC_north(end)],...
            [aus8_currents.z_bot, aus8_currents.z_bot], ...
            'm', ...
            'linewidth',line_width)
    end
    
    if sp == 3
        arrow([-32.9 -500], ...
            [aus8_currents.lat_v_SBC_north(...
            aus8_currents.lon_u_ALLC==aus8_figures.cross.lon(1,sp)) ...
            -100], 8)
        text(-32.9, -500, '$\mathcal{V}_{CC}$', 'fontsize',font_size)
        arrow([-32.9 -700], ...
            [-33.5 ...
            aus8_currents.z_mid], 8)
        text(-32.9, -700, '$\mathcal{W}$', 'fontsize',font_size)
        arrow([-32.9 -900], ...
            [aus8_currents.lat_v_SBC_south(...
            aus8_currents.lon_u_ALLC==aus8_figures.cross.lon(1,sp)) ...
            -100], 8)
        text(-32.9, -900, '$\mathcal{V}_{SBC}$', 'fontsize',font_size)
        arrow([-33.5 -1150], ...
            [aus8_currents.lat_v_DRC_south(...
            aus8_currents.lon_u_ALLC==aus8_figures.cross.lon(1,sp)) ...
            -100], 8)
        text(-33.5, -1150, {'upper', '$\mathcal{V}_{OF}$'}, ...
            'fontsize',font_size)
        arrow([-33.5 -1400], ...
            [aus8_currents.lat_v_DRC_south(...
            aus8_currents.lon_u_ALLC==aus8_figures.cross.lon(1,sp)) ...
            -1000], 8)
        text(-33.5, -1400, {'lower', '$\mathcal{V}_{OF}$'}, ...
            'fontsize',font_size)
        arrow([-33.5 -1700], ...
            [-34.5 ...
            -2000], 8)
        text(-33.5, -1700, {'$\mathcal{W}_{z_{ref}}$', '\ $=0$'}, ...
            'fontsize',font_size)
    end   
    
    title(['(' lett(sp) ') $' num2str(aus8_figures.cross.lon(1,sp)) ...
        '^{\circ}$E: ' aus8_figures.sect_names{sp}])
    grid
    set(gca,'layer','top','color',fig_color,...
        'fontsize',font_size,'tickdir','out', ...
        'ytick', -2000:200:0)
    if col_ind(sp) ~= 1, set(gca,'yticklabel',''), end
    
    if sp == rowN*colN
        ax = axes;
        set(gca,'Visible','off')
        colormap(ax, cmaps);
        cbar = colorbar;
        set(cbar,'ytick',cmaps_linspace, ...
            'YAxisLocation','right','YTickLabel',cmaps_y_label,...
            'fontsize',font_size)
        set(cbar,'units','centimeters','position', [...
            (marg_l+x_sp*(cm(sp))+gap_w*(cm(sp)-1)+plot_cbar_gap), ...
            (marg_b+y_sp*(rm(sp)-1)+gap_h*(rm(sp)-1)), ...
            cbar_x, ...
            cbar_y]);
    end
end

outputls = ls(figures_path);
scriptname = mfilename;
if ~contains(outputls, scriptname)
    mkdir(figures_path, scriptname)
end
export_fig(fig, ...
    [figures_path mfilename '/' scriptname(1:3) ...
    '_fig' num2str(fig_n) '_'], ...
    '-transparent', '-m3')
close


%%
play(bird_f_path,[1 (get(bird_f_path, 'SampleRate')*3)]);

