%% fig 2: meridional cross sections of zonal velocity differences
clearvars('-except', '*_path')
play(bird_i_path,[1 (get(bird_i_path, 'SampleRate')*3)]);

load([data_path 'SACS_data/aus8_coor'])
load([data_path 'SACS_data/aus8_currents'])
load([data_path 'SACS_data/KDau_currents'])
load([data_path 'SACS_data/KDau_fcrt'])

lat_u = aus8_coor.lat_u;
lon_u = aus8_coor.lon_u;
lat_v = aus8_coor.lat_v;
lon_v = aus8_coor.lon_v;


%%
close all
screen_ratio = 0.75;
fig_n = 1;
rowcols = [2 2];
rowcols_size = [7 4.8]/screen_ratio; % cm
margs = [1 0.2 0.8 0.4]/screen_ratio; % cm
gaps = [0.8 0.6]/screen_ratio; % cm
plot_cbar_gap = 0.5/screen_ratio;
cbar_x = 0.3/screen_ratio;
cbar_y = rowcols_size(2);
lett = 'a':'z';

font_size = 8*screen_ratio;
fig_color = [1 1 1];

fig = figure(fig_n);
rowN = rowcols(1); colN = rowcols(2);
[rm, cm] = meshgrid(rowN:-1:1, 1:colN);
x_sp = rowcols_size(1); % x subplot length
y_sp = rowcols_size(2); % y subplot length
col_ind = (repmat(1:colN,rowN,1))';
row_ind = (fliplr(repmat((1:rowN)',1,colN)))';
gap_w = gaps(1); % gap width between subplots
gap_h = gaps(2); % gap height between subplots
marg_b = margs(3); % bottom_aus8 margin
marg_t = margs(4); % top margin
marg_l = margs(1); % left margin
marg_r = margs(2); % right margin
fig_x = marg_l+colN*x_sp+gap_w*(colN-1)+marg_r;
fig_y = marg_b+rowN*y_sp+gap_h*(rowN-1)+marg_t;

desired_length = 0.05/screen_ratio; %cm
if y_sp > x_sp, long_side = y_sp; else, long_side = x_sp; end
norm_length = desired_length/long_side;
fig_tick_length = [norm_length; 0.01];
if cbar_y > cbar_x, long_side = cbar_y; else, long_side = cbar_x; end
norm_length = desired_length/long_side;
cbar_tick_length = norm_length;

set(fig,'units','centimeters','paperunits','centimeters', ...
    'inverthardcopy','off','color',fig_color,...
    'paperposition',[0 0 fig_x fig_y]*screen_ratio,...
    'position',[0 0 fig_x fig_y]);

line_width = 0.5;
dashed = 0.1;
big_line = 0;

sp = 1;
subplot_x = marg_l+x_sp*(cm(sp)-1)+gap_w*(cm(sp)-1);
subplot_y = marg_b+y_sp*(rm(sp)-1)+gap_h*(rm(sp)-1);
ax = axes('Units','centimeters', ...
    'Position',[subplot_x,subplot_y,x_sp,y_sp]);

hh = plot([124 124], [-30 30],...
    'color', [0.7 0.7 0.7], 'linewidth', line_width+0.2);
set(get(get(hh,'Annotation'),'LegendInformation'), ...
    'IconDisplayStyle','off');
hold on
hh = plot([132 132], [-30 30], 'linestyle', '--', ...
    'color', [0.7 0.7 0.7], 'linewidth', line_width+0.2);
set(get(get(hh,'Annotation'),'LegendInformation'), ...
    'IconDisplayStyle','off');
hh = plot([141 141], [-30 30], ...
    'color', [0.8 0.8 0.8], 'linewidth', line_width+0.2);
set(get(get(hh,'Annotation'),'LegendInformation'), ...
    'IconDisplayStyle','off');

plot(lon_u, aus8_currents.SBC_Ut.mean, 'k-', ...
    'linewidth', line_width+big_line)
plot(lon_u, KDau_currents.SBC_Ut.mean, 'k--', ...
    'linewidth', line_width-dashed)
plot(lon_u, KDau_fcrt.SBC_Ut.mean, 'k:', 'linewidth', line_width)

plot(lon_v, aus8_currents.SBC_Vtnc.mean, 'g-', ...
    'linewidth', line_width+big_line)
plot(lon_v, KDau_currents.SBC_Vtnc.mean, 'g--', ...
    'linewidth', line_width-dashed)
plot(lon_v, KDau_fcrt.SBC_Vtnc.mean, 'g:', 'linewidth', line_width)

text(119, 1.9, 'LCE', 'fontsize',font_size)
text(131.1, 1.9, 'SAC', 'fontsize',font_size)
text(143, 1.9, 'ZC', 'fontsize',font_size)
text(131, 1.6, 'Zonal shelf', 'fontsize',font_size, ...
    'horizontalalignment', 'right')
text(133, 1.6, 'SE diagonal shelf', 'fontsize',font_size)

axis([115 147 -2.1 2.1])
h_tit = title(['(' lett(sp) ...
    ') SBCs local zonal and cumulative CCs transports'], ...
    'fontsize',font_size, 'horizontalalignment','left');
h_tit.Position(1) = 115;

grid
h_leg = legend(...
    'ZD CARS $\mathcal{U}_{SBCs}$', ...
    'ZD KDS75 $\mathcal{U}_{SBCs}$', ...
    'Full KDS75 $\mathcal{U}_{SBCs}$', ...
    'ZD CARS $\mathcal{V}_{CCs}$', ...
    'ZD KDS75 $\mathcal{V}_{CCs}$', ...
    'Full KDS75 $\mathcal{V}_{CCs}$');

set(h_leg,'units','centimeters', 'orientation','vertical', ...
    'fontsize',font_size)
title(h_leg,['Legend (' lett(sp) ')'],'fontsize',font_size)
h_pos1 = get(h_leg,'position')/screen_ratio;
set(h_leg,'position', [...
    (marg_l+x_sp*(cm(sp))+gap_w*(cm(sp))), ...
    (marg_b+y_sp*(cm(sp)+1)+gap_h*(cm(sp))-h_pos1(4)), ...
    h_pos1(3), ...
    h_pos1(4)]);

set(ax,'layer','top','color',fig_color,...
    'fontsize',font_size,'tickdir','out',...
    'ticklength',fig_tick_length, ...
    'xtick',115:2:155,'ytick',-3:0.5:3)
if row_ind(sp) ~= rowN
    set(gca,'xticklabel','')
else
    xlabel('Longitude')
end
if col_ind(sp) == 1
    ylabel('Transport ($Sv$)')
end


sp = 3;
subplot_x = marg_l+x_sp*(cm(sp)-1)+gap_w*(cm(sp)-1);
subplot_y = marg_b+y_sp*(rm(sp)-1)+gap_h*(rm(sp)-1);
ax = axes('Units','centimeters', ...
    'Position',[subplot_x,subplot_y,x_sp,y_sp]);

hh = plot([124 124], [-30 30],...
    'color', [0.7 0.7 0.7], 'linewidth', line_width+0.2);
set(get(get(hh,'Annotation'),'LegendInformation'), ...
    'IconDisplayStyle','off');
hold on
hh = plot([132 132], [-30 30], 'linestyle', '--', ...
    'color', [0.7 0.7 0.7], 'linewidth', line_width+0.2);
set(get(get(hh,'Annotation'),'LegendInformation'), ...
    'IconDisplayStyle','off');
hh = plot([141 141], [-30 30], ...
    'color', [0.8 0.8 0.8], 'linewidth', line_width+0.2);
set(get(get(hh,'Annotation'),'LegendInformation'), ...
    'IconDisplayStyle','off');

plot(lon_v, aus8_currents.SBC_Vtsc.mean, 'r-', ...
    'linewidth', line_width+big_line)
plot(lon_v, KDau_currents.SBC_Vtsc.mean, 'r--', ...
    'linewidth', line_width-dashed)
plot(lon_v, KDau_fcrt.SBC_Vtsc.mean, 'r:', 'linewidth', line_width)

plot(lon_v, aus8_currents.SBC_Wtc_real.mean, 'b-', ...
    'linewidth', line_width+big_line)
plot(lon_v, KDau_currents.SBC_Wtc_real.mean, 'b--', ...
    'linewidth', line_width-dashed)
plot(lon_v, KDau_fcrt.SBC_Wtc.mean, 'b:', 'linewidth', line_width)

axis([115 147 -2.1 2.1])
h_tit = title(['(' lett(sp-1) ...
    ') SBCs cumulative transports with the FC'], ...
    'fontsize',font_size, 'horizontalalignment','left');
h_tit.Position(1) = 115;

grid
h_leg = legend(...
    'ZD CARS $\mathcal{V}_{SBCs}$', ...
    'ZD KDS75 $\mathcal{V}_{SBCs}$', ...
    'Full KDS75 $\mathcal{V}_{SBCs}$', ...
    'ZD CARS $\mathcal{W}_{SBCs}$', ...
    'ZD KDS75 $\mathcal{W}_{SBCs}$', ...
    'Full KDS75 $\mathcal{W}_{SBCs}$');

set(h_leg,'units','centimeters', 'orientation','vertical', ...
    'fontsize',font_size)
title(h_leg,['Legend (' lett(sp-1) ')'],'fontsize',font_size)
h_pos1 = get(h_leg,'position')/screen_ratio;
set(h_leg,'position', [...
    (marg_l+x_sp*(cm(sp))+gap_w*(cm(sp))), ...
    (marg_b+y_sp*(cm(sp))+gap_h*(cm(sp))), ...
    h_pos1(3), ...
    h_pos1(4)]);

set(ax,'layer','top','color',fig_color,...
    'fontsize',font_size,'tickdir','out',...
    'ticklength',fig_tick_length, ...
    'xtick',115:2:155,'ytick',-3:0.5:3)
if row_ind(sp) ~= rowN
    set(gca,'xticklabel','')
else
    xlabel('Longitude')
end
if col_ind(sp) == 1
    ylabel('Transport ($Sv$)')
end


sp = 4;
subplot_x = marg_l+x_sp*(cm(sp)-1)+gap_w*(cm(sp)-1);
subplot_y = marg_b+y_sp*(rm(sp)-1)+gap_h*(rm(sp)-1);
ax = axes('Units','centimeters', ...
    'Position',[subplot_x,subplot_y,x_sp,y_sp]);

hh = plot([124 124], [-30 30],...
    'color', [0.7 0.7 0.7], 'linewidth', line_width+0.2);
set(get(get(hh,'Annotation'),'LegendInformation'), ...
    'IconDisplayStyle','off');
hold on
hh = plot([132 132], [-30 30], 'linestyle', '--', ...
    'color', [0.7 0.7 0.7], 'linewidth', line_width+0.2);
set(get(get(hh,'Annotation'),'LegendInformation'), ...
    'IconDisplayStyle','off');
hh = plot([141 141], [-30 30], ...
    'color', [0.8 0.8 0.8], 'linewidth', line_width+0.2);
set(get(get(hh,'Annotation'),'LegendInformation'), ...
    'IconDisplayStyle','off');

plot(lon_u, aus8_currents.DRC_Ut.mean, 'k-', ...
    'linewidth', line_width+big_line)
plot(lon_u, KDau_currents.DRC_Ut.mean, 'k--', ...
    'linewidth', line_width-dashed)
plot(lon_u, KDau_fcrt.DRC_Ut.mean, 'k:', 'linewidth', line_width)
plot(lon_v, aus8_currents.DRC_Vtnc.mean, 'r-', ...
    'linewidth', line_width+big_line)
plot(lon_v, KDau_currents.DRC_Vtnc.mean, 'r--', ...
    'linewidth', line_width-dashed)
plot(lon_v, KDau_fcrt.DRC_Vtnc.mean, 'r:', 'linewidth', line_width)
plot(lon_v, aus8_currents.DRC_Vtsc.mean, 'm-', ...
    'linewidth', line_width+big_line)
plot(lon_v, KDau_currents.DRC_Vtsc.mean, 'm--', ...
    'linewidth', line_width-dashed)
plot(lon_v, KDau_fcrt.DRC_Vtsc.mean, 'm:', 'linewidth', line_width)
plot(lon_v, aus8_currents.DRC_Wtc_real.mean, 'b-', ...
    'linewidth', line_width+big_line)
plot(lon_v, KDau_currents.DRC_Wtc_real.mean, 'b--', ...
    'linewidth', line_width-dashed)
plot(lon_v, KDau_fcrt.DRC_Wtc.mean, 'b:', 'linewidth', line_width)
plot(lon_v, KDau_fcrt.BOT_Wtc.mean, 'c:', 'linewidth', line_width)

axis([115 147 -16.2 2.6])
h_tit = title(['(' lett(sp-1) ...
    ') FC local zonal and cumulative horiz. and vert. transports'], ...
    'fontsize',font_size, 'horizontalalignment','left');
h_tit.Position(1) = 115;

grid
h_leg = legend(...
    'ZD CARS $\mathcal{U}_{FC}$', ...
    'ZD KDS75 $\mathcal{U}_{FC}$', ...
    'Full KDS75 $\mathcal{U}_{FC}$', ...
    'ZD CARS $\mathcal{V}_{FC}$', ...
    'ZD KDS75 $\mathcal{V}_{FC}$', ...
    'Full KDS75 $\mathcal{V}_{FC}$', ...
    'ZD CARS $\mathcal{V}_{OFs}$', ...
    'ZD KDS75 $\mathcal{V}_{OFs}$', ...
    'Full KDS75 $\mathcal{V}_{OFs}$', ...
    'ZD CARS $\mathcal{W}_{FC}$', ...
    'ZD KDS75 $\mathcal{W}_{FC}$', ...
    'Full KDS75 $\mathcal{W}_{FC}$', ...
    'Full KDS75 $\mathcal{W}_{bot}$');
set(h_leg,'units','centimeters', 'orientation','vertical', ...
    'fontsize',font_size)
title(h_leg,['Legend (' lett(sp-1) ')'],'fontsize',font_size)
h_pos1 = get(h_leg,'position')/screen_ratio;
set(h_leg,'position', [...
    (marg_l+x_sp*(cm(sp))+gap_w*(cm(sp)-1)-h_pos1(3)), ...
    (marg_b+y_sp*(cm(sp)-1)+gap_h*(cm(sp)-1)), ...
    h_pos1(3), ...
    h_pos1(4)]);

set(ax,'layer','top','color',fig_color,...
    'fontsize',font_size,'tickdir','out',...
    'ticklength',fig_tick_length, ...
    'xtick',115:2:155,'ytick',-20:2:20)
if row_ind(sp) ~= rowN
    set(gca,'xticklabel','')
else
    xlabel('Longitude')
end
if col_ind(sp) == 1
    ylabel('Transport ($Sv$)')
end

outputls = ls(figures_path);
scriptname = mfilename;
if ~contains(outputls, scriptname)
    mkdir(figures_path, scriptname)
end
print(fig, ...
    [figures_path mfilename '/' scriptname(1:3) ...
    '_fig' num2str(fig_n) '_'], ...
    '-dpng', '-r300')
print(fig, ...
    ['~/Duran2017/SACS/10319442jbhpxfsdfvwy/' scriptname(1:3) ...
    '_fig' num2str(fig_n) '_'], ...
    '-dpng', '-r300')
close all


%%
play(bird_f_path,[1 (get(bird_f_path, 'SampleRate')*3)]);

