%% fig 2: meridional cross sections of zonal velocity differences
clearvars('-except', '*_path')
play(bird_i_path,[1 (get(bird_i_path, 'SampleRate')*3)]);

load([data_path 'SACS_data/aus8_coor'])
load([data_path 'SACS_data/aus8_currents'])
load([data_path 'SACS_data/KDau_currents'])


%%
lat_u = aus8_coor.lat_u;
lon_u = aus8_coor.lon_u;
lat_v = aus8_coor.lat_v;
lon_v = aus8_coor.lon_v;


%%
close all
screen_ratio = 0.75;
fig_n = 1;
rowcols = [4 1];
rowcols_size = [7 4]/screen_ratio; % cm
margs = [0.6 0.2 0.6 0.4]/screen_ratio; % cm
gaps = [1 0.6]/screen_ratio; % cm
plot_cbar_gap = 0.1/screen_ratio;
cbar_x = 0.3/screen_ratio;
cbar_y = rowcols_size(2);
lett = 'a':'z';

font_size = 8*screen_ratio;
fig_color = [1 1 1];

fig = figure(fig_n);
rowN = rowcols(1); colN = rowcols(2);
[rm, cm] = meshgrid(rowN:-1:1, 1:colN);
x_sp = rowcols_size(1); % x subplot length
y_sp = rowcols_size(2); % y subplot length
col_ind = (repmat(1:colN,rowN,1))';
row_ind = (fliplr(repmat((1:rowN)',1,colN)))';
gap_w = gaps(1); % gap width between subplots
gap_h = gaps(2); % gap height between subplots
marg_b = margs(3); % bottom_aus8 margin
marg_t = margs(4); % top margin
marg_l = margs(1); % left margin
marg_r = margs(2); % right margin
set(fig,'units','centimeters','paperunits','centimeters', ...
    'inverthardcopy','off','color',[1 1 1],...
    'paperposition',[0 0 ...
    (marg_l+colN*x_sp+gap_w*(colN-1)+marg_r) ...
    (marg_b+rowN*y_sp+gap_h*(rowN-1)+marg_t)]*screen_ratio,...
    'position',[0 0 ...
    (marg_l+colN*x_sp+gap_w*(colN-1)+marg_r) ...
    (marg_b+rowN*y_sp+gap_h*(rowN-1)+marg_t)]);

line_width = 0.5;

sp = 1;
ax = axes('Units','centimeters', ...
    'Position',[...
    (marg_l+x_sp*(cm(sp)-1)+gap_w*(cm(sp)-1)), ...
    (marg_b+y_sp*(rm(sp)-1)+gap_h*(rm(sp)-1)), ...
    x_sp, ...
    y_sp]);

plot(lon_u, aus8_currents.SBC_Ut, 'k-', 'linewidth', line_width)
hold on
plot(lon_u, KDau_currents.SBC_Ut, 'k--', 'linewidth', line_width)

axis([115 147 -2.2 3.6])
h_tit = title(['(' lett(sp) ') SBC local zonal transport ($Sv$)'], ...
    'fontsize',font_size, 'horizontalalignment','left');
h_tit.Position(1) = 115;

grid
h_leg = legend(...
    'CARS $\mathcal{U}_{SBC}$', ...
    'KDS75 $\mathcal{U}_{SBC}$');
set(h_leg,'units','centimeters', 'orientation','vertical', ...
    'fontsize',font_size)
h_pos1 = get(h_leg,'position')/screen_ratio;
set(h_leg,'position', [...
    (marg_l+x_sp*(cm(sp)-1)+gap_w*(cm(sp)-1)), ...
    (marg_b+y_sp*(rm(sp))+gap_h*(rm(sp)-1)-h_pos1(4)), ...
    h_pos1(3), ...
    h_pos1(4)]);
set(ax,'layer','top','color',fig_color,...
    'fontsize',font_size,'tickdir','out',...
    'xtick',115:2:155,'ytick',-3:0.5:3)
if row_ind(sp) ~= rowN, set(gca,'xticklabel',''), end


sp = 2;
ax = axes('Units','centimeters', ...
    'Position',[...
    (marg_l+x_sp*(cm(sp)-1)+gap_w*(cm(sp)-1)), ...
    (marg_b+y_sp*(rm(sp)-1)+gap_h*(rm(sp)-1)), ...
    x_sp, ...
    y_sp]);
plot(lon_v, aus8_currents.SBC_Vtnc, 'g-', 'linewidth', line_width)
hold on
plot(lon_v, KDau_currents.SBC_Vtnc, 'g--', 'linewidth', line_width)
plot(lon_v, aus8_currents.SBC_Vtsc, 'r-', 'linewidth', line_width)
plot(lon_v, KDau_currents.SBC_Vtsc, 'r--', 'linewidth', line_width)
plot(lon_v, aus8_currents.SBC_Wtc_real, 'b-', 'linewidth', line_width)
plot(lon_v, KDau_currents.SBC_Wtc_real, 'b--', 'linewidth', line_width)

axis([115 147 -2.2 3.6])
h_tit = title(['(' lett(sp) ...
    ') SBC cumulated inward/outward transport ($Sv$)'], ...
    'fontsize',font_size, 'horizontalalignment','left');
h_tit.Position(1) = 115;
grid
h_leg = legend(...
    'CARS $\mathcal{V}_{CC}$', ...
    'KDS75 $\mathcal{V}_{CC}$', ...
    'CARS $\mathcal{V}_{SBC}$', ...
    'KDS75 $\mathcal{V}_{SBC}$', ...
    'CARS $\mathcal{W}_{SBC}$', ...
    'KDS75 $\mathcal{W}_{SBC}$');
set(h_leg,'units','centimeters', 'orientation','vertical', ...
    'fontsize',font_size)
h_pos1 = get(h_leg,'position')/screen_ratio;
set(h_leg,'position', [...
    (marg_l+x_sp*(cm(sp)-1)+gap_w*(cm(sp)-1)), ...
    (marg_b+y_sp*(rm(sp))+gap_h*(rm(sp)-1)-h_pos1(4)), ...
    h_pos1(3), ...
    h_pos1(4)]);
set(ax,'layer','top','color',fig_color,...
    'fontsize',font_size,'tickdir','out',...
    'xtick',115:2:155,'ytick',-3:0.5:3)
if row_ind(sp) ~= rowN, set(gca,'xticklabel',''), end

sp = 3;
ax = axes('Units','centimeters', ...
    'Position',[...
    (marg_l+x_sp*(cm(sp)-1)+gap_w*(cm(sp)-1)), ...
    (marg_b+y_sp*(rm(sp)-1)+gap_h*(rm(sp)-1)), ...
    x_sp, ...
    y_sp]);

plot(lon_u, aus8_currents.DRC_Ut, 'k-', 'linewidth', line_width)
hold on
plot(lon_u, KDau_currents.DRC_Ut, 'k--', 'linewidth', line_width)

axis([115 147 -16.2 2.6])
h_tit = title(['(' lett(sp) ...
    ') FC local zonal transport ($Sv$)'], ...
    'fontsize',font_size, 'horizontalalignment','left');
h_tit.Position(1) = 115;
grid
h_leg = legend(...
    'CARS $\mathcal{U}_{FC}$', ...
    'KDS75 $\mathcal{U}_{FC}$');
set(h_leg,'units','centimeters', 'orientation','vertical', ...
    'fontsize',font_size)
h_pos1 = get(h_leg,'position')/screen_ratio;
set(h_leg,'position', [...
    (marg_l+x_sp*(cm(sp)-1)+gap_w*(cm(sp)-1)), ...
    (marg_b+y_sp*(rm(sp))+gap_h*(rm(sp)-1)-h_pos1(4)), ...
    h_pos1(3), ...
    h_pos1(4)]);
set(ax,'layer','top','color',fig_color,...
    'fontsize',font_size,'tickdir','out',...
    'xtick',115:2:155,'ytick',-20:2:20)
if row_ind(sp) ~= rowN, set(gca,'xticklabel',''), end


sp = 4;
ax = axes('Units','centimeters', ...
    'Position',[...
    (marg_l+x_sp*(cm(sp)-1)+gap_w*(cm(sp)-1)), ...
    (marg_b+y_sp*(rm(sp)-1)+gap_h*(rm(sp)-1)), ...
    x_sp, ...
    y_sp]);
plot(lon_v, aus8_currents.DRC_Vtnc, 'r-', 'linewidth', line_width)
hold on
plot(lon_v, KDau_currents.DRC_Vtnc, 'r--', 'linewidth', line_width)
plot(lon_v, aus8_currents.DRC_Vtsc, 'm-', 'linewidth', line_width)
plot(lon_v, KDau_currents.DRC_Vtsc, 'm--', 'linewidth', line_width)
plot(lon_v, aus8_currents.DRC_Wtc_real, 'b-', 'linewidth', line_width)
plot(lon_v, KDau_currents.DRC_Wtc_real, 'b--', 'linewidth', line_width)

axis([115 147 -16.2 2.6])
h_tit = title(['(' lett(sp) ...
    ') FC cumulated inward/outward transport ($Sv$)'], ...
    'fontsize',font_size, 'horizontalalignment','left');
h_tit.Position(1) = 115;
grid
h_leg = legend(...
    'CARS $\mathcal{V}_{FC}$', ...
    'KDS75 $\mathcal{V}_{FC}$', ...
    'CARS $\mathcal{V}_{OF}$', ...
    'KDS75 $\mathcal{V}_{OF}$', ...
    'CARS $\mathcal{W}_{FC}$', ...
    'KDS75 $\mathcal{W}_{FC}$');
set(h_leg,'units','centimeters', 'orientation','vertical', ...
    'fontsize',font_size)
h_pos1 = get(h_leg,'position')/screen_ratio;
set(h_leg,'position', [...
    (marg_l+x_sp*(cm(sp)-1)+gap_w*(cm(sp)-1)), ...
    (marg_b+y_sp*(rm(sp)-1)+gap_h*(rm(sp)-1)), ...
    h_pos1(3), ...
    h_pos1(4)]);
set(ax,'layer','top','color',fig_color,...
    'fontsize',font_size,'tickdir','out',...
    'xtick',115:2:155,'ytick',-20:2:20)
if row_ind(sp) ~= rowN, set(gca,'xticklabel',''), end

outputls = ls(figures_path);
scriptname = mfilename;
if ~contains(outputls, scriptname)
    mkdir(figures_path, scriptname)
end
print(fig, ...
    [figures_path mfilename '/' scriptname(1:3) ...
    '_fig' num2str(fig_n) '_'], ...
    '-dpng', '-r300')
close all

%%
play(bird_f_path,[1 (get(bird_f_path, 'SampleRate')*3)]);

