%%
clearvars('-except', '*_path')

load([data_path 'SACS_data/aus8_coor'])
load([data_path 'SACS_data/KDau_thet'])
load([data_path 'SACS_data/KDau_salt'])

lat = aus8_coor.lat;
lon = aus8_coor.lon;
depth = aus8_coor.depth;
Months = aus8_coor.Months;
pres = aus8_coor.pres;


%% Calculate conservative temperature, absolute salinity
% make templates
[KDau_asal.mean, KDau_rho.mean] = ...
    deal(NaN([length(lat) length(lon) length(depth)]));
for t = 1 : 12
    KDau_asal.(Months{t}) = ...
        NaN([length(lat), length(lon), length(depth)]);
    KDau_rho.(Months{t}) = ...
        NaN([length(lat), length(lon), length(depth)]);
end

% Calculate using functions from Gibbs seawater toolbox TEOS-10
for p = 1 : length(pres)
    % Mean absolute salinity and conservative temperature from
    % practical salinity and in-situ temperature
    KDau_asal.mean(:,:,p) = gsw_SA_from_SP(...
        KDau_salt.mean(:,:,p),pres(p),lon,lat);
    
    for t = 1 : 12
        KDau_asal.(Months{t})(:,:,p) = gsw_SA_from_SP(...
            KDau_salt.(Months{t})(:,:,p),pres(p),lon,lat);
    end
    fprintf('z = %4.0f \n',depth(p))
end


% Calculate density
for p = 1 : length(pres)
    KDau_rho.mean(:,:,p) = gsw_rho(...
        KDau_asal.mean(:,:,p),...
        KDau_thet.mean(:,:,p),pres(p));
    
    for t = 1 : 12
        KDau_rho.(Months{t})(:,:,p) = gsw_rho(...
            KDau_asal.(Months{t})(:,:,p),...
            KDau_thet.(Months{t})(:,:,p),pres(p));
    end
end


%% mean figure
fig_n = 1;
rowcols = [3 3];
rowcols_size = [8 5]; % cm
margs = [1 1 1 1]; % cm
gaps = [1 1]; % cm

for sp = 1 : rowcols(1)*rowcols(2)
    axis_setup{sp} = ...
        [aus8_coor.lon(1) aus8_coor.lon(end) ...
        aus8_coor.lat(end) aus8_coor.lat(1)];
    x{sp} = aus8_coor.lon;
    y{sp} = aus8_coor.lat;
end
    
z_ind = {0 0 0 -400 -400 -400 -1000 -1000 -1000};
data = {...
    KDau_thet.mean(:,:,depth==z_ind{1}), ...
    KDau_asal.mean(:,:,depth==z_ind{2}), ...
    KDau_rho.mean(:,:,depth==z_ind{3}), ...
    KDau_thet.mean(:,:,depth==z_ind{4}), ...
    KDau_asal.mean(:,:,depth==z_ind{5}), ...
    KDau_rho.mean(:,:,depth==z_ind{6}), ...
    KDau_thet.mean(:,:,depth==z_ind{7}), ...
    KDau_asal.mean(:,:,depth==z_ind{8}), ...
    KDau_rho.mean(:,:,depth==z_ind{9})};
minmax = {...
    [8 20], ...
    [34 36], ...
    [min(min(data{3})) 1026.8], ...    
    [min(min(data{4}))+2 max(max(data{4}))-2], ...
    [min(min(data{5}))+0.2 max(max(data{5}))-0.2], ...
    [1028.5 1028.8], ...    
    [min(min(data{7})) max(max(data{7}))], ...
    [min(min(data{8})) max(max(data{8}))], ...
    [min(min(data{9})) max(max(data{9}))]};
cmaps_levels = 12;
cmaps = {...
    flipud(othercolor('RdYlBu8', cmaps_levels)), ...
    flipud(othercolor('PuOr8', cmaps_levels)), ...
    othercolor('BrBG8', cmaps_levels), ...
    flipud(othercolor('RdYlBu8', cmaps_levels)), ...
    flipud(othercolor('PuOr8', cmaps_levels)), ...
    othercolor('BrBG8', cmaps_levels), ...
    flipud(othercolor('RdYlBu8', cmaps_levels)), ...
    flipud(othercolor('PuOr8', cmaps_levels)), ...
    othercolor('BrBG8', cmaps_levels)};
titles = {...
    ['KDS75 mean $temp$ $z=' num2str(z_ind{1}) '$ ($^{\circ}C$)'], ...
    ['KDS75 mean $salt$ $z=' num2str(z_ind{2}) '$ ($psu$)'], ...
    ['KDS75 mean $rho$ $z=' num2str(z_ind{3}) '$ ($kg/m^3$)'], ...
    ['KDS75 mean $temp$ $z=' num2str(z_ind{4}) '$ ($^{\circ}C$)'], ...
    ['KDS75 mean $salt$ $z=' num2str(z_ind{5}) '$ ($psu$)'], ...
    ['KDS75 mean $rho$ $z=' num2str(z_ind{6}) '$ ($kg/m^3$)'], ...
    ['KDS75 mean $temp$ $z=' num2str(z_ind{7}) '$ ($^{\circ}C$)'], ...
    ['KDS75 mean $salt$ $z=' num2str(z_ind{8}) '$ ($psu$)'], ...
    ['KDS75 mean $rho$ $z=' num2str(z_ind{9}) '$ ($kg/m^3$)']};
font_size = 9;
fig_color = [0.7 0.7 0.7];

fig = pcolor_maker(...
    fig_n, rowcols, rowcols_size, margs, gaps, ...
    x, y, data, axis_setup, minmax, cmaps, ...
    titles, font_size, fig_color);
outputls = ls(figures_path);
scriptname = mfilename;
if ~contains(outputls, scriptname)
    mkdir(figures_path, scriptname)
end
export_fig(fig, ...
    [figures_path mfilename '/' scriptname(1:3) ...
    '_fig' num2str(fig_n) '_'], ...
    '-m3')
close


%%
save([data_path 'SACS_data/KDau_asal'], 'KDau_asal')
save([data_path 'SACS_data/KDau_rho'], 'KDau_rho')
disp('KDau_asal KDau_rho DONE')

