%% calc t s and rho
clearvars('-except', '*_path')

load([data_path 'SACS_data/aus8_coor'])
load([data_path 'SACS_data/KDS75_thet'])
load([data_path 'SACS_data/KDS75_salt'])

lat = aus8_coor.lat;
lon = aus8_coor.lon;
depth = aus8_coor.depth;
Months = aus8_coor.Months;
KDS_lat = KDS75_thet.lat;
KDS_lon = KDS75_thet.lon;
KDS_depth = KDS75_thet.depth;
KDS_depth(1) = 0;


%% interp2: same lat/lon first
[KDau_thet_dum.mean, KDau_salt_dum.mean] = ...
    deal(NaN([length(lat) length(lon) length(KDS_depth)]));
for t = 1 : 12
    KDau_thet_dum.(Months{t}) = ...
        NaN([length(lat), length(lon), length(KDS_depth)]);
    KDau_salt_dum.(Months{t}) = ...
        NaN([length(lat), length(lon), length(KDS_depth)]);
end

for p = 1 : length(KDS_depth)
    KDau_thet_dum.mean(:,:,p) = interp2(KDS_lon, KDS_lat, ...
        KDS75_thet.mean(:,:,p), lon, lat);
    KDau_salt_dum.mean(:,:,p) = interp2(KDS_lon, KDS_lat, ...
        KDS75_salt.mean(:,:,p), lon, lat);
    
    for t = 1 : 12
        KDau_thet_dum.(Months{t})(:,:,p) = interp2(KDS_lon, KDS_lat, ...
            KDS75_thet.(Months{t})(:,:,p), lon, lat);
        KDau_salt_dum.(Months{t})(:,:,p) = interp2(KDS_lon, KDS_lat, ...
            KDS75_salt.(Months{t})(:,:,p), lon, lat);
    end
    fprintf('depth = %7.3f \n',KDS_depth(p))
end


%% interp1: same depth second (this takes a long time to run!)
% make templates
[KDau_thet.mean, KDau_salt.mean] = ...
    deal(NaN([length(lat) length(lon) length(depth)]));
for t = 1 : 12
    KDau_thet.(Months{t}) = ...
        NaN([length(lat), length(lon), length(depth)]);
    KDau_salt.(Months{t}) = ...
        NaN([length(lat), length(lon), length(depth)]);
end

aus8_coor.KDS75_bottom_depth = NaN([length(lat), length(lon)]);

for m = 1 : length(lat)
    for n = 1 : length(lon)
        KDau_thet.mean(m,n,:) = interp1(KDS_depth, ...
            squeeze(KDau_thet_dum.mean(m,n,:)), depth);
        KDau_salt.mean(m,n,:) = interp1(KDS_depth, ...
            squeeze(KDau_salt_dum.mean(m,n,:)), depth);
        
        last_finite = ...
            find(isfinite(squeeze(KDau_thet.mean(m,n,:))), ...
            1, 'last');
        if ~isempty(last_finite)
            aus8_coor.KDS75_bottom_depth(m,n) = depth(last_finite);
        end
        
        for t = 1 : 12
            KDau_thet.(Months{t})(m,n,:) = interp1(KDS_depth, ...
                squeeze(KDau_thet_dum.(Months{t})(m,n,:)), depth);
            KDau_salt.(Months{t})(m,n,:) = interp1(KDS_depth, ...
                squeeze(KDau_salt_dum.(Months{t})(m,n,:)), depth);
        end
    end
    fprintf('lat = %7.3f \n',lat(m))
end


%% mean
fig_n = 1;
rowcols = [3 2];
rowcols_size = [8 5]; % cm
margs = [1 1 1 1]; % cm
gaps = [1 1]; % cm

for sp = 1 : rowcols(1)*rowcols(2)
    axis_setup{sp} = ...
        [aus8_coor.lon(1) aus8_coor.lon(end) ...
        aus8_coor.lat(end) aus8_coor.lat(1)];
    x{sp} = aus8_coor.lon;
    y{sp} = aus8_coor.lat;
end
    
z = {0 0 -400 -400 -1000 -1000};
for p = 1 : length(z)
    z_ind{p} = find_nearest(aus8_coor.depth,z{p});
end

data = {...
    KDau_thet.mean(:,:,z_ind{1}), ...
    KDau_salt.mean(:,:,z_ind{2}), ...
    KDau_thet.mean(:,:,z_ind{3}), ...
    KDau_salt.mean(:,:,z_ind{4}), ...
    KDau_thet.mean(:,:,z_ind{5}), ...
    KDau_salt.mean(:,:,z_ind{6})};
minmax = {...
    [8 20], ...
    [34 36], ...
    [7.5 11], ...
    [34.4 34.88], ...
    [2.8 5.6], ...
    [34.32 34.47]};
cmaps_levels = 12;
cmaps = {...
    flipud(othercolor('RdYlBu8', cmaps_levels)), ...
    flipud(othercolor('PuOr8', cmaps_levels)), ...
    flipud(othercolor('RdYlBu8', cmaps_levels)), ...
    flipud(othercolor('PuOr8', cmaps_levels)), ...
    flipud(othercolor('RdYlBu8', cmaps_levels)), ...
    flipud(othercolor('PuOr8', cmaps_levels))};
titles = {...
    ['KDS75 on aus8 mean $thet$ $z=' ...
    num2str(aus8_coor.depth(z_ind{1})) '$ ($^{\circ}C$)'], ...
    ['KDS75 on aus8 mean $salt$ $z=' ...
    num2str(aus8_coor.depth(z_ind{2})) '$ ($psu$)'], ...
    ['KDS75 on aus8 mean $thet$ $z=' ...
    num2str(aus8_coor.depth(z_ind{3})) '$ ($^{\circ}C$)'], ...
    ['KDS75 on aus8 mean $salt$ $z=' ...
    num2str(aus8_coor.depth(z_ind{4})) '$ ($psu$)'], ...
    ['KDS75 on aus8 mean $thet$ $z=' ...
    num2str(aus8_coor.depth(z_ind{5})) '$ ($^{\circ}C$)'], ...
    ['KDS75 on aus8 mean $salt$ $z=' ...
    num2str(aus8_coor.depth(z_ind{6})) '$ ($psu$)']};
font_size = 9;
fig_color = [0.7 0.7 0.7];

fig = pcolor_maker(...
    fig_n, rowcols, rowcols_size, margs, gaps, ...
    x, y, data, axis_setup, minmax, cmaps, ...
    titles, font_size, fig_color);
outputls = ls(figures_path);
scriptname = mfilename;
if ~contains(outputls, scriptname)
    mkdir(figures_path, scriptname)
end
export_fig(fig, ...
    [figures_path mfilename '/' scriptname(1:3) ...
    '_fig' num2str(fig_n) '_'], ...
    '-m3')
close


%% seas var temp
fig_n = 2;
rowcols = [3 4];
rowcols_size = [8 5]; % cm
margs = [1 1 1 1]; % cm
gaps = [1 1]; % cm

z = {0 0 0 0 -400 -400 -400 -400 -1000 -1000 -1000 -1000};
for p = 1 : length(z)
    z_ind{p} = find_nearest(depth,z{p});
end

month_ind = {'Jan', 'Apr', 'Jul', 'Oct', 'Jan', 'Apr', 'Jul', 'Oct', ...
    'Jan', 'Apr', 'Jul', 'Oct',};
cmaps_levels = 12;

for sp = 1 : rowcols(1)*rowcols(2)
    x{sp} = lon;
    y{sp} = lat;
    axis_setup{sp} = ...
        [lon(1) lon(end) ...
        lat(end) lat(1)];
    data{sp} = KDau_thet.(month_ind{sp})(:,:,z_ind{sp});
    titles{sp} = ['KDS75 on aus8 ' month_ind{sp} ...
        ' $thet$ $z=' ...
        num2str(depth(z_ind{sp})) '$ ($^{\circ}C$)'];
    cmaps{sp} = flipud(othercolor('RdYlBu8', cmaps_levels));
end

minmax = {...
    [8 20], ...
    [8 20], ...
    [8 20], ...
    [8 20], ...
    [7.5 11], ...
    [7.5 11], ...
    [7.5 11], ...
    [7.5 11], ...
    [2.8 5.6], ...
    [2.8 5.6], ...
    [2.8 5.6], ...
    [2.8 5.6]};

font_size = 9;
fig_color = [0.7 0.7 0.7];

fig = pcolor_maker(...
    fig_n, rowcols, rowcols_size, margs, gaps, ...
    x, y, data, axis_setup, minmax, cmaps, ...
    titles, font_size, fig_color);
outputls = ls(figures_path);
scriptname = mfilename;
if ~contains(outputls, scriptname)
    mkdir(figures_path, scriptname)
end
export_fig(fig, ...
    [figures_path mfilename '/' scriptname(1:3) ...
    '_fig' num2str(fig_n) '_'], ...
    '-m3')
close


%% seas var salt
fig_n = 3;
rowcols = [3 4];
rowcols_size = [8 5]; % cm
margs = [1 1 1 1]; % cm
gaps = [1 1]; % cm

z = {0 0 0 0 -400 -400 -400 -400 -1000 -1000 -1000 -1000};
for p = 1 : length(z)
    z_ind{p} = find_nearest(depth,z{p});
end

month_ind = {'Jan', 'Apr', 'Jul', 'Oct', 'Jan', 'Apr', 'Jul', 'Oct', ...
    'Jan', 'Apr', 'Jul', 'Oct',};
cmaps_levels = 12;

for sp = 1 : rowcols(1)*rowcols(2)
    x{sp} = lon;
    y{sp} = lat;
    axis_setup{sp} = ...
        [lon(1) lon(end) ...
        lat(end) lat(1)];
    data{sp} = KDau_salt.(month_ind{sp})(:,:,z_ind{sp});
    titles{sp} = ['KDS75 on aus8 ' month_ind{sp} ...
        ' $salt$ $z=' ...
        num2str(depth(z_ind{sp})) '$ ($psu$)'];
    cmaps{sp} = flipud(othercolor('PuOr8', cmaps_levels));
end

minmax = {...
    [34 36], ...
    [34 36], ...
    [34 36], ...
    [34 36], ...
    [34.4 34.88], ...
    [34.4 34.88], ...
    [34.4 34.88], ...
    [34.4 34.88], ...
    [34.32 34.47], ...
    [34.32 34.47], ...
    [34.32 34.47], ...
    [34.32 34.47]};

font_size = 9;
fig_color = [0.7 0.7 0.7];

fig = pcolor_maker(...
    fig_n, rowcols, rowcols_size, margs, gaps, ...
    x, y, data, axis_setup, minmax, cmaps, ...
    titles, font_size, fig_color);
outputls = ls(figures_path);
scriptname = mfilename;
if ~contains(outputls, scriptname)
    mkdir(figures_path, scriptname)
end
export_fig(fig, ...
    [figures_path mfilename '/' scriptname(1:3) ...
    '_fig' num2str(fig_n) '_'], ...
    '-m3')
close



%%
save([data_path 'SACS_data/KDau_thet'], 'KDau_thet')
save([data_path 'SACS_data/KDau_salt'], 'KDau_salt')
disp('KDau_thet KDau_salt DONE')

