%% Calculate conservative temperature Theta, absolute salinity asal,
clearvars('-except', '*_path')

load([data_path 'SACS_data/aus8_coor'])
load([data_path 'SACS_data/aus8_temp'])
load([data_path 'SACS_data/aus8_salt'])

lat = aus8_coor.lat;
lon = aus8_coor.lon;
Months = aus8_coor.Months;
depth = aus8_coor.depth;
pres = gsw_p_from_z(depth,-40);
aus8_coor.pres = pres;
save([data_path 'SACS_data/aus8_coor'], 'aus8_coor')


%% Calculate conservative temperature, absolute salinity
% make templates
[aus8_asal.mean, aus8_thet.mean, aus8_rho.mean] = ...
    deal(NaN([length(lat) length(lon) length(depth)]));
for t = 1 : 12
    aus8_asal.(Months{t}) = ...
        NaN([length(lat), length(lon), length(depth)]);
    aus8_thet.(Months{t}) = ...
        NaN([length(lat), length(lon), length(depth)]);
    aus8_rho.(Months{t}) = ...
        NaN([length(lat), length(lon), length(depth)]);
end

% Calculate using functions from Gibbs seawater toolbox TEOS-10
for p = 1 : length(pres)
    % Mean absolute salinity and conservative temperature from
    % practical salinity and in-situ temperature
    aus8_asal.mean(:,:,p) = gsw_SA_from_SP(...
        aus8_salt.mean(:,:,p),pres(p),lon,lat);
    aus8_thet.mean(:,:,p) = gsw_CT_from_t(...
        aus8_asal.mean(:,:,p),...
        aus8_temp.mean(:,:,p),pres(p));
    
    for t = 1 : 12
        aus8_asal.(Months{t})(:,:,p) = gsw_SA_from_SP(...
            aus8_salt.(Months{t})(:,:,p),pres(p),lon,lat);
        
        aus8_thet.(Months{t})(:,:,p) = gsw_CT_from_t(...
            aus8_asal.(Months{t})(:,:,p),...
            aus8_temp.(Months{t})(:,:,p),pres(p));
    end
    fprintf('z = %4.0f \n',depth(p))
end


% Calculate density
for p = 1 : length(pres)
    aus8_rho.mean(:,:,p) = gsw_rho(...
        aus8_asal.mean(:,:,p),...
        aus8_thet.mean(:,:,p),pres(p));
    
    for t = 1 : 12
        aus8_rho.(Months{t})(:,:,p) = gsw_rho(...
            aus8_asal.(Months{t})(:,:,p),...
            aus8_thet.(Months{t})(:,:,p),pres(p));
    end
end


%% mean figure
fig_n = 1;
rowcols = [3 3];
rowcols_size = [8 5]; % cm
margs = [1 1 1 1]; % cm
gaps = [1 1]; % cm

for sp = 1 : rowcols(1)*rowcols(2)
    axis_setup{sp} = ...
        [aus8_coor.lon(1) aus8_coor.lon(end) ...
        aus8_coor.lat(end) aus8_coor.lat(1)];
    x{sp} = aus8_coor.lon;
    y{sp} = aus8_coor.lat;
end
    
z_ind = {0 0 0 -400 -400 -400 -1000 -1000 -1000};
data = {...
    aus8_thet.mean(:,:,depth==z_ind{1}), ...
    aus8_salt.mean(:,:,depth==z_ind{2}), ...
    aus8_rho.mean(:,:,depth==z_ind{3}), ...
    aus8_thet.mean(:,:,depth==z_ind{4}), ...
    aus8_salt.mean(:,:,depth==z_ind{5}), ...
    aus8_rho.mean(:,:,depth==z_ind{6}), ...
    aus8_thet.mean(:,:,depth==z_ind{7}), ...
    aus8_salt.mean(:,:,depth==z_ind{8}), ...
    aus8_rho.mean(:,:,depth==z_ind{9})};
minmax = {...
    [8 20], ...
    [34 36], ...
    [min(min(data{3})) 1026.8], ...    
    [7.5 11], ...
    [34.4 34.88], ...
    [1028.5 1028.8], ...    
    [2.8 5.6], ...
    [34.32 34.47], ...
    [min(min(data{9})) max(max(data{9}))]};
cmaps_levels = 12;
cmaps = {...
    flipud(othercolor('RdYlBu8', cmaps_levels)), ...
    flipud(othercolor('PuOr8', cmaps_levels)), ...
    othercolor('BrBG8', cmaps_levels), ...
    flipud(othercolor('RdYlBu8', cmaps_levels)), ...
    flipud(othercolor('PuOr8', cmaps_levels)), ...
    othercolor('BrBG8', cmaps_levels), ...
    flipud(othercolor('RdYlBu8', cmaps_levels)), ...
    flipud(othercolor('PuOr8', cmaps_levels)), ...
    othercolor('BrBG8', cmaps_levels)};
titles = {...
    ['aus8 mean $temp$ $z=' num2str(z_ind{1}) '$ ($^{\circ}C$)'], ...
    ['aus8 mean $salt$ $z=' num2str(z_ind{2}) '$ ($psu$)'], ...
    ['aus8 mean $rho$ $z=' num2str(z_ind{3}) '$ ($kg/m^3$)'], ...
    ['aus8 mean $temp$ $z=' num2str(z_ind{4}) '$ ($^{\circ}C$)'], ...
    ['aus8 mean $salt$ $z=' num2str(z_ind{5}) '$ ($psu$)'], ...
    ['aus8 mean $rho$ $z=' num2str(z_ind{6}) '$ ($kg/m^3$)'], ...
    ['aus8 mean $temp$ $z=' num2str(z_ind{7}) '$ ($^{\circ}C$)'], ...
    ['aus8 mean $salt$ $z=' num2str(z_ind{8}) '$ ($psu$)'], ...
    ['aus8 mean $rho$ $z=' num2str(z_ind{9}) '$ ($kg/m^3$)']};
font_size = 9;
fig_color = [0.7 0.7 0.7];

fig = pcolor_maker(...
    fig_n, rowcols, rowcols_size, margs, gaps, ...
    x, y, data, axis_setup, minmax, cmaps, ...
    titles, font_size, fig_color);
outputls = ls(figures_path);
scriptname = mfilename;
if ~contains(outputls, scriptname)
    mkdir(figures_path, scriptname)
end
export_fig(fig, ...
    [figures_path mfilename '/' scriptname(1:3) ...
    '_fig' num2str(fig_n) '_'], ...
    '-m3')
close


%% save the structure
save([data_path 'SACS_data/aus8_asal'], 'aus8_asal')
save([data_path 'SACS_data/aus8_thet'], 'aus8_thet')
save([data_path 'SACS_data/aus8_rho'], 'aus8_rho')

disp('aus8_asal aus8_thet aus8_rho DONE')

