%% make anomaly
clearvars('-except', '*_path')

load([data_path 'SACS_data/aus8_coor'])
aus8_coor_names = fieldnames(aus8_coor);
a = aus8_coor;
load([data_path 'SACS_data/KDau_fulu'])
load([data_path 'SACS_data/KDau_fulv'])


%%
u_mean = KDau_fulu.mean*100;
v_mean = KDau_fulv.mean*100;

u_mean_bot = zeros(size(u_mean(:,:,1)));
for x = 1:length(aus8_coor.lon_u)
    for y = 1:length(aus8_coor.lat_u)
        u_mean_bot_idx = find(isfinite(u_mean(y,x,:)), 1, 'last');
        
        if ~isempty(u_mean_bot_idx)
            u_mean_bot(y,x) = u_mean(y,x,u_mean_bot_idx);
        end
    end
end

v_mean_bot = zeros(size(v_mean(:,:,1)));
for x = 1:length(aus8_coor.lon_v)
    for y = 1:length(aus8_coor.lat_v)
        v_mean_bot_idx = find(isfinite(v_mean(y,x,:)), 1, 'last');
        
        if ~isempty(v_mean_bot_idx)
            v_mean_bot(y,x) = v_mean(y,x,v_mean_bot_idx);
        end
    end
end

v_mean_bot_interp2 = interp2(...
    aus8_coor.lon_v, aus8_coor.lat_v, v_mean_bot, ...
    aus8_coor.lon_u, aus8_coor.lat_u);

speed = sqrt(u_mean_bot.^2 + v_mean_bot_interp2.^2);

close all
pcolor(aus8_coor.lon_u, aus8_coor.lat_u, speed);
colormap(jet(10))
caxis([0 10])
shading interp
% axis ij
colorbar
title('Current speed in $cm/s$ in MOM01 at the sea bottom or at 2000 m depth, whichever is shallowest')

%%
fig_n = 1;
rowcols = [3 2];
rowcols_size = [8 5]; % cm
margs = [1 1 1 1]; % cm
gaps = [1 1]; % cm

for sp = 1 : rowcols(1)*rowcols(2)
    axis_setup{sp} = ...
        [a.lon(1) a.lon(end) ...
        a.lat(end) a.lat(1)];
    x{sp} = a.lon;
    y{sp} = a.lat;
end
    
z = {0 0 -400 -400 -1000 -1000};
for p = 1 : length(z)
    z_ind{p} = find_nearest(a.depth,z{p});
end

data = {...
    b.thet.mean(:,:,z_ind{1}), ...
    b.salt.mean(:,:,z_ind{2}), ...
    b.thet.mean(:,:,z_ind{3}), ...
    b.salt.mean(:,:,z_ind{4}), ...
    b.thet.mean(:,:,z_ind{5}), ...
    b.salt.mean(:,:,z_ind{6})};
minmax = {...
    [-1.5 1.5], ...
    [-0.6 0.6], ...
    [-1.5 1.5], ...
    [-0.2 0.2], ...
    [-1.5 1.5], ...
    [-0.1 0.1]};
cmaps_levels = 12;
cmaps = {...
    flipud(othercolor('RdYlBu8', cmaps_levels)), ...
    flipud(othercolor('PuOr8', cmaps_levels)), ...
    flipud(othercolor('RdYlBu8', cmaps_levels)), ...
    flipud(othercolor('PuOr8', cmaps_levels)), ...
    flipud(othercolor('RdYlBu8', cmaps_levels)), ...
    flipud(othercolor('PuOr8', cmaps_levels))};
titles = {...
    ['aus8 - KDS75 mean $thet$ $z=' ...
    num2str(aus8_coor.depth(z_ind{1})) '$ ($^{\circ}C$)'], ...
    ['aus8 - KDS75 mean $salt$ $z=' ...
    num2str(aus8_coor.depth(z_ind{2})) '$ ($psu$)'], ...
    ['aus8 - KDS75 mean $thet$ $z=' ...
    num2str(aus8_coor.depth(z_ind{3})) '$ ($^{\circ}C$)'], ...
    ['aus8 - KDS75 mean $salt$ $z=' ...
    num2str(aus8_coor.depth(z_ind{4})) '$ ($psu$)'], ...
    ['aus8 - KDS75 mean $thet$ $z=' ...
    num2str(aus8_coor.depth(z_ind{5})) '$ ($^{\circ}C$)'], ...
    ['aus8 - KDS75 mean $salt$ $z=' ...
    num2str(aus8_coor.depth(z_ind{6})) '$ ($psu$)']};
font_size = 9;
fig_color = [0.7 0.7 0.7];

fig = pcolor_maker(...
    fig_n, rowcols, rowcols_size, margs, gaps, ...
    x, y, data, axis_setup, minmax, cmaps, ...
    titles, font_size, fig_color);
outputls = ls(figures_path);
scriptname = mfilename;
if ~contains(outputls, scriptname)
    mkdir(figures_path, scriptname)
end
export_fig(fig, ...
    [figures_path mfilename '/' scriptname(1:3) ...
    '_fig' num2str(fig_n) '_'], ...
    '-m3')
close


%% seas var temp
fig_n = 2;
rowcols = [3 4];
rowcols_size = [8 5]; % cm
margs = [1 1 1 1]; % cm
gaps = [1 1]; % cm

z = {0 0 0 0 -400 -400 -400 -400 -1000 -1000 -1000 -1000};
for p = 1 : length(z)
    z_ind{p} = find_nearest(a.depth,z{p});
end

month_ind = {'Jan', 'Apr', 'Jul', 'Oct', 'Jan', 'Apr', 'Jul', 'Oct', ...
    'Jan', 'Apr', 'Jul', 'Oct',};
cmaps_levels = 12;

for sp = 1 : rowcols(1)*rowcols(2)
    x{sp} = a.lon;
    y{sp} = a.lat;
    axis_setup{sp} = ...
        [a.lon(1) a.lon(end) ...
        a.lat(end) a.lat(1)];
    data{sp} = b.thet.(month_ind{sp})(:,:,z_ind{sp});
    titles{sp} = ['aus8 - KDS75 ' month_ind{sp} ...
        ' $thet$ $z=' ...
        num2str(a.depth(z_ind{sp})) '$ ($^{\circ}C$)'];
    cmaps{sp} = flipud(othercolor('RdYlBu8', cmaps_levels));
end

minmax = {...
    [-1.5 1.5], ...
    [-1.5 1.5], ...
    [-1.5 1.5], ...
    [-1.5 1.5], ...
    [-1.5 1.5], ...
    [-1.5 1.5], ...
    [-1.5 1.5], ...
    [-1.5 1.5], ...
    [-1.5 1.5], ...
    [-1.5 1.5], ...
    [-1.5 1.5], ...
    [-1.5 1.5]};

font_size = 9;
fig_color = [0.7 0.7 0.7];

fig = pcolor_maker(...
    fig_n, rowcols, rowcols_size, margs, gaps, ...
    x, y, data, axis_setup, minmax, cmaps, ...
    titles, font_size, fig_color);
outputls = ls(figures_path);
scriptname = mfilename;
if ~contains(outputls, scriptname)
    mkdir(figures_path, scriptname)
end
export_fig(fig, ...
    [figures_path mfilename '/' scriptname(1:3) ...
    '_fig' num2str(fig_n) '_'], ...
    '-m3')
close


%% seas var salt
fig_n = 3;
rowcols = [3 4];
rowcols_size = [8 5]; % cm
margs = [1 1 1 1]; % cm
gaps = [1 1]; % cm

z = {0 0 0 0 -400 -400 -400 -400 -1000 -1000 -1000 -1000};
for p = 1 : length(z)
    z_ind{p} = find_nearest(a.depth,z{p});
end

month_ind = {'Jan', 'Apr', 'Jul', 'Oct', 'Jan', 'Apr', 'Jul', 'Oct', ...
    'Jan', 'Apr', 'Jul', 'Oct',};
cmaps_levels = 12;

for sp = 1 : rowcols(1)*rowcols(2)
    x{sp} = a.lon;
    y{sp} = a.lat;
    axis_setup{sp} = ...
        [a.lon(1) a.lon(end) ...
        a.lat(end) a.lat(1)];
    data{sp} = b.salt.(month_ind{sp})(:,:,z_ind{sp});
    titles{sp} = ['aus8 - KDS75 ' month_ind{sp} ...
        ' $salt$ $z=' ...
        num2str(a.depth(z_ind{sp})) '$ ($psu$)'];
    cmaps{sp} = flipud(othercolor('PuOr8', cmaps_levels));
end

minmax = {...
    [-0.6 0.6], ...
    [-0.6 0.6], ...
    [-0.6 0.6], ...
    [-0.6 0.6], ...
    [-0.2 0.2], ...
    [-0.2 0.2], ...
    [-0.2 0.2], ...
    [-0.2 0.2], ...
    [-0.1 0.1], ...
    [-0.1 0.1], ...
    [-0.1 0.1], ...
    [-0.1 0.1]};

font_size = 9;
fig_color = [0.7 0.7 0.7];

fig = pcolor_maker(...
    fig_n, rowcols, rowcols_size, margs, gaps, ...
    x, y, data, axis_setup, minmax, cmaps, ...
    titles, font_size, fig_color);
outputls = ls(figures_path);
scriptname = mfilename;
if ~contains(outputls, scriptname)
    mkdir(figures_path, scriptname)
end
export_fig(fig, ...
    [figures_path mfilename '/' scriptname(1:3) ...
    '_fig' num2str(fig_n) '_'], ...
    '-m3')
close


%%

