% close all
figure

n = 4;
u_0 = zeros(size(data_contour{sp}(depth_plot_idx,1:n:end)));
quiver(x_contour{sp}(1:n:end),(1:0.5:11)*10, ...
    data_contour{sp}(depth_plot_idx,1:n:end), ...
    fulw{sp}(depth_plot_idx,1:n:end)*1000000, ...
    'k','autoscale','off')

% axis([-50,-44,-2500,0])

figure
n = 4;
u_0 = zeros(size(data_contour{sp}(depth_plot_idx,1:n:end)));
h = quiver(x_contour{sp}(1:n:end),(1:0.5:11), ...
    data_contour{sp}(depth_plot_idx,1:n:end), ...
    fulw{sp}(depth_plot_idx,1:n:end)*100000, ...
    'k','autoscale','off');