%% fig 2: meridional cross sections of zonal velocity differences
clc
path(pathdef)

% set up main directory
cd ~
% cd /home/z5100174/Desktop/MATLAB

% Add path to the data to be loaded
addpath(genpath('Dropbox/SACS_work'))
addpath(genpath(['/Users/earl/Dropbox/' ...
    'LeeuwinUndercurrent_HonoursProject/' ...
    'matlab/OFAM/ofam_out']))

clear 
% vn is a function that can store the name of a variable
% hence vn(x) returns 'x' as a string.
vn = @(x) inputname(1);

load aus8_geostrophy

load ofam_mean


%% load stuff
lat_CARS = aus8_TEOS10.lat;
lon_CARS = aus8_TEOS10.lon;
pres = aus8_TEOS10.pres;

lat_u_CARS = aus8_geostrophy.u.lat_u;
lon_u_CARS = lon_CARS;
u_CARS = aus8_geostrophy.u.u_0_HH;

lat_OFAM = ofam_mean.lat;
lon_OFAM = ofam_mean.lon;

lat_u_OFAM = lat_OFAM;
lon_u_OFAM = lon_OFAM;
u_OFAM = ofam_mean.u_vel;

u_interp2_OFAM = NaN(length(lat_u_CARS), length(lon_u_CARS), length(pres));
for kk = 1 : length(pres)
    u_interp2_OFAM(:,:,kk) = interp2(lon_OFAM, lat_OFAM, ...
        u_OFAM(:,:,kk), lon_u_CARS, lat_u_CARS);

end
u_OFAM_minus_CARS = u_interp2_OFAM - u_CARS;


%% plot map
% 1) figure set-up
close all
font_size = 6;
fig1 = figure(1);
set(gcf, 'units', 'normalized', 'outerposition', [0 0 0.35 0.6]);
rowN = 2; colN = 2;
col_ind = (repmat(1:colN,rowN,1))';
row_ind = (fliplr(repmat((1:rowN)',1,colN)))';
gap_w = -0.05; % gap width between subplots
gap_h = 0.06; % gap height between subplots
marg_b = 0.03; % bottom margin
marg_t = 0.03; % top margin
marg_l = 0.05; % left margin
marg_r = 0.02; % right margin
x_sp = (1 - marg_l - marg_r - gap_w*(colN-1))/colN; % x subplot length
y_sp = (1 - marg_b - marg_t - gap_h*(rowN-1))/rowN; % y subplot length
h_axes_sp = tight_subplot(rowN, colN, ...
    [gap_h gap_w], [marg_b marg_t], [marg_l marg_r]);
colormap(flipud(othercolor('RdBu11')))

% 2) all data set-up
sp = 1;
axes(h_axes_sp(sp))
lon_now = 115;
lon_now_ind = lon_u_CARS == lon_now;
u_OFAM_now = squeeze(u_interp2_OFAM(:,lon_now_ind,:))';
u_OFAM_minus_CARS_now = squeeze(u_OFAM_minus_CARS(:,lon_now_ind,:))';

% 3) asal pcolor set-up
u_OFAM_minus_CARS_contours = -0.225:0.025:0.225;
u_OFAM_minus_CARS_contours_tick = u_OFAM_minus_CARS_contours(2:end-1);
cmap_levels = length(u_OFAM_minus_CARS_contours);
cmap = flipud(othercolor('RdBu11', cmap_levels-1));
cmap([(cmap_levels-1)/2 (cmap_levels-1)/2+1], :) = [1 1 1; 1 1 1];
colormap(h_axes_sp(sp), cmap);

% 4) plot asal pcolor
pcolor(...
    lat_u_CARS, ...
    pres, ...
    u_OFAM_minus_CARS_now)
shading interp
axis ij
hold on
caxis([u_OFAM_minus_CARS_contours(1) u_OFAM_minus_CARS_contours(end)]);
axis([-39.5 -34.5 0 2000])
cbar = colorbar;
set(cbar, 'visible', 'off');

% 5) Theta contours set-up
u_OFAM_pos_contours = 0.05:0.05:0.5;
u_OFAM_neg_contours = -0.05:-0.05:-0.5;
u_OFAM_zero_contours = [0 0];

% 6) plot Theta labelled contours
[c, h] = contour(...
    lat_u_CARS, ...
    pres, ...
    u_OFAM_now, ...
    u_OFAM_pos_contours, ...
    '-k', ...
    'linewidth',0.5);
clabel(c,h, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')
[c, h] = contour(...
    lat_u_CARS, ...
    pres, ...
    u_OFAM_now, ...
    u_OFAM_neg_contours, ...
    '--k', ...
    'linewidth',0.5);
clabel(c,h, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')
[c, h] = contour(...
    lat_u_CARS, ...
    pres, ...
    u_OFAM_now, ...
    u_OFAM_zero_contours, ...
    '-k', ...
    'linewidth',1);
clabel(c,h, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')

% 7) title, grid, background and fonts
title(['Leeuwin Current and Flinders Current at ' ...
    num2str(lon_now) '\circE'])
grid
set(gca,'layer','top','color',[0.7 0.7 0.7],...
    'fontsize',font_size,'fontweight','bold')
if col_ind(sp) ~= 1, set(gca,'yticklabel',''), end


% 8) 2nd subplot: OFAM @ surface
sp = 2;
axes(h_axes_sp(sp))
lon_now = 130;
lon_now_ind = lon_u_CARS == lon_now;
u_OFAM_now = squeeze(u_interp2_OFAM(:,lon_now_ind,:))';
u_OFAM_minus_CARS_now = squeeze(u_OFAM_minus_CARS(:,lon_now_ind,:))';
colormap(h_axes_sp(sp), cmap);
pcolor(...
    lat_u_CARS, ...
    pres, ...
    u_OFAM_minus_CARS_now)
shading interp
axis ij
hold on
caxis([u_OFAM_minus_CARS_contours(1) u_OFAM_minus_CARS_contours(end)]);
axis([-36.5 -31.5 0 2000])
cbar = colorbar;
set(cbar, 'visible', 'off');
[c, h] = contour(...
    lat_u_CARS, ...
    pres, ...
    u_OFAM_now, ...
    u_OFAM_pos_contours, ...
    '-k', ...
    'linewidth',0.5);
clabel(c,h, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')
[c, h] = contour(...
    lat_u_CARS, ...
    pres, ...
    u_OFAM_now, ...
    u_OFAM_neg_contours, ...
    '--k', ...
    'linewidth',0.5);
clabel(c,h, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')
[c, h] = contour(...
    lat_u_CARS, ...
    pres, ...
    u_OFAM_now, ...
    u_OFAM_zero_contours, ...
    '-k', ...
    'linewidth',1);
clabel(c,h, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')
title(['South Australian Current and Flinders Current at ' ...
    num2str(lon_now) '\circE'])
grid
set(gca,'layer','top','color',[0.7 0.7 0.7],...
    'fontsize',font_size,'fontweight','bold')
if col_ind(sp) ~= 1, set(gca,'yticklabel',''), end

% 9) 3rd subplot: CARS @ 400dbars
sp = 3;
axes(h_axes_sp(sp))
lon_now = 143;
lon_now_ind = lon_u_CARS == lon_now;
u_OFAM_now = squeeze(u_interp2_OFAM(:,lon_now_ind,:))';
u_OFAM_minus_CARS_now = squeeze(u_OFAM_minus_CARS(:,lon_now_ind,:))';
colormap(h_axes_sp(sp), cmap);
pcolor(...
    lat_u_CARS, ...
    pres, ...
    u_OFAM_minus_CARS_now)
shading interp
axis ij
hold on
caxis([u_OFAM_minus_CARS_contours(1) u_OFAM_minus_CARS_contours(end)]);
axis([-43.5 -38.5 0 2000])
cbar = colorbar;
set(cbar, 'visible', 'off');
[c, h] = contour(...
    lat_u_CARS, ...
    pres, ...
    u_OFAM_now, ...
    u_OFAM_pos_contours, ...
    '-k', ...
    'linewidth',0.5);
clabel(c,h, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')
[c, h] = contour(...
    lat_u_CARS, ...
    pres, ...
    u_OFAM_now, ...
    u_OFAM_neg_contours, ...
    '--k', ...
    'linewidth',0.5);
clabel(c,h, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')
[c, h] = contour(...
    lat_u_CARS, ...
    pres, ...
    u_OFAM_now, ...
    u_OFAM_zero_contours, ...
    '-k', ...
    'linewidth',1);
clabel(c,h, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')
title(['Zeehan Current and Flinders Current at ' ...
    num2str(lon_now) '\circE'])
grid
set(gca,'layer','top','color',[0.7 0.7 0.7],...
    'fontsize',font_size,'fontweight','bold')
if col_ind(sp) ~= 1, set(gca,'yticklabel',''), end

% 10) 4th subplot: OFAM @ 400fdb
sp = 4;
axes(h_axes_sp(sp))
lon_now = 147;
lon_now_ind = lon_u_CARS == lon_now;
u_OFAM_now = squeeze(u_interp2_OFAM(:,lon_now_ind,:))';
u_OFAM_minus_CARS_now = squeeze(u_OFAM_minus_CARS(:,lon_now_ind,:))';
colormap(h_axes_sp(sp), cmap);
pcolor(...
    lat_u_CARS, ...
    pres, ...
    u_OFAM_minus_CARS_now)
shading interp
axis ij
hold on
caxis([u_OFAM_minus_CARS_contours(1) u_OFAM_minus_CARS_contours(end)]);
axis([-48.5 -43.5 0 2000])
cbar = colorbar;
cbarrow
set(cbar, 'YTick', ...
    u_OFAM_minus_CARS_contours_tick(...
    u_OFAM_minus_CARS_contours_tick~=0));

[c, h] = contour(...
    lat_u_CARS, ...
    pres, ...
    u_OFAM_now, ...
    u_OFAM_pos_contours, ...
    '-k', ...
    'linewidth',0.5);
clabel(c,h, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')
[c, h] = contour(...
    lat_u_CARS, ...
    pres, ...
    u_OFAM_now, ...
    u_OFAM_neg_contours, ...
    '--k', ...
    'linewidth',0.5);
clabel(c,h, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')
[c, h] = contour(...
    lat_u_CARS, ...
    pres, ...
    u_OFAM_now, ...
    u_OFAM_zero_contours, ...
    '-k', ...
    'linewidth',1);
clabel(c,h, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')
title(['Zeehan Current and Tasman Leakage at ' ...
    num2str(lon_now) '\circE'])
grid
set(gca,'layer','top','color',[0.7 0.7 0.7],...
    'fontsize',font_size,'fontweight','bold')
if col_ind(sp) ~= 1, set(gca,'yticklabel',''), end

% 11) Save
export_fig(fig1, ['Dropbox/SACS_work/figures/f02_xsections_zonaldiff/u' ...
    ], ...
    '-m4', '-nocrop')
close

