%% fig 2: meridional cross sections of zonal velocity differences
clearvars('-except', 'outputpath')

load aus8_ZD_method
load aus8_currents


%% load stuff
pres = aus8_ZD_method.pres_mid;

lat_u = aus8_ZD_method.lat_u;
lon_u = aus8_ZD_method.lon_u;
u_g_prime = aus8_ZD_method.u_g_prime;

lat_v = aus8_ZD_method.lat_v;
lon_v = aus8_ZD_method.lon_v;
v_g_prime = aus8_ZD_method.v_g_prime;

v_g_prime_interp2 = NaN(length(lat_v), length(lon_u), length(pres));
for kk = 1 : length(pres)
    v_g_prime_interp2(:,:,kk) = interp2(...
        lon_v, lat_v, v_g_prime(:,:,kk), lon_u, lat_v);
end


%% plot map
% 1) figure set-up
close all
font_size = 6;
fig1 = figure(1);
set(gcf, 'units', 'normalized', 'outerposition', [0 0 0.35 0.6]);
rowN = 2; colN = 2;
col_ind = (repmat(1:colN,rowN,1))';
row_ind = (fliplr(repmat((1:rowN)',1,colN)))';
gap_w = 0.03; % gap width between subplots
gap_h = 0.06; % gap height between subplots
marg_b = 0.03; % bottom margin
marg_t = 0.03; % top margin
marg_l = 0.05; % left margin
marg_r = 0.02; % right margin
x_sp = (1 - marg_l - marg_r - gap_w*(colN-1))/colN; % x subplot length
y_sp = (1 - marg_b - marg_t - gap_h*(rowN-1))/rowN; % y subplot length
h_axes_sp = tight_subplot(rowN, colN, ...
    [gap_h gap_w], [marg_b marg_t], [marg_l marg_r]);

% 2) all data set-up
sp = 1;
axes(h_axes_sp(sp))
lon_now = 115;
lon_now_ind = lon_u == lon_now;
u_g_prime_now = squeeze(u_g_prime(:,lon_now_ind,:))';
v_g_prime_now = squeeze(v_g_prime_interp2(:,lon_now_ind,:))';

% 3) u pcolor setup
magnif = 100;
Reds_cont = ...
    [0 0.01 0.02 0.05 0.1 0.2 0.5 1]*magnif;
% Blues_cont = ...
%     [0 0.01 0.02 0.05 0.1 0.2 0.5 1]*magnif;
Blues_cont = ...
    -fliplr(Reds_cont);
BluesReds_cont = [Blues_cont(1:end-1), Reds_cont];
levels = length(BluesReds_cont)-1;
BluesReds = flipud(othercolor('RdBu11', levels));
BluesReds([levels/2, levels/2+1],:) = [1 1 1; 1 1 1];
cmap_custom = cmapcust(BluesReds,BluesReds_cont);
colormap(h_axes_sp(sp), cmap_custom);

% 4) plot u pcolor
pcolor(...
    lat_u, ...
    pres, ...
    u_g_prime_now*magnif)
shading interp
axis ij
hold on
caxis([BluesReds_cont(1) BluesReds_cont(end)]);
axis([-39.5 -34.5 0 2000])

% 5) v contours set-up
delta = 0.02;
v_g_prime_pos_contours = delta:delta:0.5;
v_g_prime_neg_contours = -delta:-delta:-0.5;
v_g_prime_zero_contours = [0 0];

% 6) plot v labelled contours
c = contour(...
    lat_v, ...
    pres, ...
    v_g_prime_now, ...
    v_g_prime_pos_contours, ...
    '-k', ...
    'linewidth',0.5);
clabel(c, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')
c = contour(...
    lat_v, ...
    pres, ...
    v_g_prime_now, ...
    v_g_prime_neg_contours, ...
    '--k', ...
    'linewidth',0.5);
clabel(c, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')
c = contour(...
    lat_v, ...
    pres, ...
    v_g_prime_now, ...
    v_g_prime_zero_contours, ...
    '-k', ...
    'linewidth',1);
clabel(c, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')

% 7) title, grid, background and fonts
title(['Leeuwin Current and Flinders Current at ' ...
    num2str(lon_now) '\circE'])
grid
set(gca,'layer','top','color',[0.7 0.7 0.7],...
    'fontsize',font_size,'fontweight','bold')
if col_ind(sp) ~= 1, set(gca,'yticklabel',''), end

% 8) 2nd subplot: OFAM @ surface
sp = 2;
axes(h_axes_sp(sp))
lon_now = 130;
lon_now_ind = lon_u == lon_now;
u_g_prime_now = squeeze(u_g_prime(:,lon_now_ind,:))';
v_g_prime_now = squeeze(v_g_prime_interp2(:,lon_now_ind,:))';
colormap(h_axes_sp(sp), cmap_custom);
pcolor(...
    lat_u, ...
    pres, ...
    u_g_prime_now*magnif)
shading interp
axis ij
hold on
caxis([BluesReds_cont(1) BluesReds_cont(end)]);
axis([-36.5 -31.5 0 2000])
c = contour(...
    lat_v, ...
    pres, ...
    v_g_prime_now, ...
    v_g_prime_pos_contours, ...
    '-k', ...
    'linewidth',0.5);
clabel(c, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')
c = contour(...
    lat_v, ...
    pres, ...
    v_g_prime_now, ...
    v_g_prime_neg_contours, ...
    '--k', ...
    'linewidth',0.5);
clabel(c, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')
c = contour(...
    lat_v, ...
    pres, ...
    v_g_prime_now, ...
    v_g_prime_zero_contours, ...
    '-k', ...
    'linewidth',1);
clabel(c, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')
title(['South Australian Current and Flinders Current at ' ...
    num2str(lon_now) '\circE'])
grid
set(gca,'layer','top','color',[0.7 0.7 0.7],...
    'fontsize',font_size,'fontweight','bold')
if col_ind(sp) ~= 1, set(gca,'yticklabel',''), end

% 9) 3rd subplot: CARS @ 400dbars
sp = 3;
axes(h_axes_sp(sp))
lon_now = 143;
lon_now_ind = lon_u == lon_now;
u_g_prime_now = squeeze(u_g_prime(:,lon_now_ind,:))';
v_g_prime_now = squeeze(v_g_prime_interp2(:,lon_now_ind,:))';
colormap(h_axes_sp(sp), cmap_custom);
pcolor(...
    lat_u, ...
    pres, ...
    u_g_prime_now*magnif)
shading interp
axis ij
hold on
caxis([BluesReds_cont(1) BluesReds_cont(end)]);
axis([-43.5 -38.5 0 2000])
c = contour(...
    lat_v, ...
    pres, ...
    v_g_prime_now, ...
    v_g_prime_pos_contours, ...
    '-k', ...
    'linewidth',0.5);
clabel(c, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')
c = contour(...
    lat_v, ...
    pres, ...
    v_g_prime_now, ...
    v_g_prime_neg_contours, ...
    '--k', ...
    'linewidth',0.5);
clabel(c, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')
c = contour(...
    lat_v, ...
    pres, ...
    v_g_prime_now, ...
    v_g_prime_zero_contours, ...
    '-k', ...
    'linewidth',1);
clabel(c, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')
title(['Zeehan Current and Flinders Current at ' ...
    num2str(lon_now) '\circE'])
grid
set(gca,'layer','top','color',[0.7 0.7 0.7],...
    'fontsize',font_size,'fontweight','bold')
if col_ind(sp) ~= 1, set(gca,'yticklabel',''), end

% 10) 4th subplot: OFAM @ 400fdb
sp = 4;
axes(h_axes_sp(sp))
lon_now = 147;
lon_now_ind = lon_u == lon_now;
u_g_prime_now = squeeze(u_g_prime(:,lon_now_ind,:))';
v_g_prime_now = squeeze(v_g_prime_interp2(:,lon_now_ind,:))';
colormap(h_axes_sp(sp), cmap_custom);
pcolor(...
    lat_u, ...
    pres, ...
    u_g_prime_now*magnif)
shading interp
axis ij
hold on
caxis([BluesReds_cont(1) BluesReds_cont(end)]);
axis([-48.5 -43.5 0 2000])
c = contour(...
    lat_v, ...
    pres, ...
    v_g_prime_now, ...
    v_g_prime_pos_contours, ...
    '-k', ...
    'linewidth',0.5);
clabel(c, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')
c = contour(...
    lat_v, ...
    pres, ...
    v_g_prime_now, ...
    v_g_prime_neg_contours, ...
    '--k', ...
    'linewidth',0.5);
clabel(c, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')
c = contour(...
    lat_v, ...
    pres, ...
    v_g_prime_now, ...
    v_g_prime_zero_contours, ...
    '-k', ...
    'linewidth',1);
clabel(c, ...
    'fontsize', font_size-1, ...
    'fontweight', 'bold')
title(['Zeehan Current and Tasman Leakage at ' ...
    num2str(lon_now) '\circE'])
grid
set(gca,'layer','top','color',[0.7 0.7 0.7],...
    'fontsize',font_size,'fontweight','bold')
if col_ind(sp) ~= 1, set(gca,'yticklabel',''), end

% 11) Save
export_fig(fig1, [outputpath 'f06_xsection_zonalflows/u' ...
    ], ...
    '-m4', '-nocrop')


%% 12) colorbar figure
fig2 = figure(2);
set(gcf, 'units', 'normalized', 'outerposition', [0 0 0.35 0.6]/2);
rowN = 1; colN = 1;
col_ind = (repmat(1:colN,rowN,1))';
row_ind = (fliplr(repmat((1:rowN)',1,colN)))';
gap_w = 0.03; % gap width between subplots
gap_h = 0.06; % gap height between subplots
marg_b = 0.03; % bottom margin
marg_t = 0.03; % top margin
marg_l = 0.05; % left margin
marg_r = 0.02; % right margin
x_sp = (1 - marg_l - marg_r - gap_w*(colN-1))/colN; % x subplot length
y_sp = (1 - marg_b - marg_t - gap_h*(rowN-1))/rowN; % y subplot length
h_axes_sp = tight_subplot(rowN, colN, ...
    [gap_h gap_w], [marg_b marg_t], [marg_l marg_r]);

axes(h_axes_sp(1))
cmap = colormap(h_axes_sp(1), BluesReds);
caxis([BluesReds_cont(1) BluesReds_cont(end)]);
cbar = colorbar;
set(gca,'visible','off')
BluesReds_linspace = ...
    linspace(BluesReds_cont(1), BluesReds_cont(end), levels+1);
set(cbar, ...
    'YTick',BluesReds_linspace(BluesReds_linspace~=0), ...
    'YTickLabel',BluesReds_cont(BluesReds_cont~=0)/magnif, ...
    'fontsize',font_size,'fontweight','bold');
export_fig(fig2, [outputpath 'f06_xsection_zonalflows/u_cbar' ...
    ], ...
    '-m2')
close all

